//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservuary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventarizations
    {
        public Nullable<System.DateTime> invent_data { get; set; }
        public int location_ID { get; set; }
        public int tank_ID { get; set; }
        public string tank_NAME { get; set; }
        public Nullable<int> inventory_NUM { get; set; }
        public string point { get; set; }
        public string ofice { get; set; }
        public string opc_TAG { get; set; }
        public Nullable<double> value_m3 { get; set; }
        public Nullable<int> tech_min_mm { get; set; }
        public Nullable<int> tech_max_mm { get; set; }
        public Nullable<int> dirID_start { get; set; }
        public Nullable<int> dirID_end { get; set; }
        public Nullable<int> oil_level { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<double> volume20 { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<double> density { get; set; }
        public Nullable<double> volumeTrue { get; set; }
        public Nullable<double> oilMass { get; set; }
        public int ID { get; set; }
    
        public virtual location location { get; set; }
    }
}
