//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservuary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KepDataLoggerEntities : DbContext
    {
        public KepDataLoggerEntities()
            : base("name=KepDataLoggerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GomelNS1_Level_Tank100_1> GomelNS1_Level_Tank100_1 { get; set; }
        public virtual DbSet<GomelNS1_Level_Tank100_2> GomelNS1_Level_Tank100_2 { get; set; }
        public virtual DbSet<GomelNS1_Level_Tank400_1> GomelNS1_Level_Tank400_1 { get; set; }
        public virtual DbSet<GomelNS1_Level_TankLeak12> GomelNS1_Level_TankLeak12 { get; set; }
        public virtual DbSet<GomelNS1_Level_TankLeak20> GomelNS1_Level_TankLeak20 { get; set; }
        public virtual DbSet<GomelNS2_Level_Tank400_2> GomelNS2_Level_Tank400_2 { get; set; }
        public virtual DbSet<GomelNS2_Level_TankLeak40_1> GomelNS2_Level_TankLeak40_1 { get; set; }
        public virtual DbSet<GomelNS2_Level_TankLeak40_2> GomelNS2_Level_TankLeak40_2 { get; set; }
        public virtual DbSet<GomelScr_Level_TankLeak30> GomelScr_Level_TankLeak30 { get; set; }
        public virtual DbSet<GorkiNS2_Level_TankLeak25_1> GorkiNS2_Level_TankLeak25_1 { get; set; }
        public virtual DbSet<GorkiNS2_Level_TankLeak25_2> GorkiNS2_Level_TankLeak25_2 { get; set; }
        public virtual DbSet<KobrinNS1_Level_TankLeak12> KobrinNS1_Level_TankLeak12 { get; set; }
        public virtual DbSet<KobrinNS2_Level_TankLeak100_1> KobrinNS2_Level_TankLeak100_1 { get; set; }
        public virtual DbSet<KobrinNS2_Level_TankLeak100_2> KobrinNS2_Level_TankLeak100_2 { get; set; }
        public virtual DbSet<KobrinNS2_Level_TankLeak200_1> KobrinNS2_Level_TankLeak200_1 { get; set; }
        public virtual DbSet<KobrinNS2_Level_TankLeak200_2> KobrinNS2_Level_TankLeak200_2 { get; set; }
        public virtual DbSet<MozAdam_km441_Level_Leak25> MozAdam_km441_Level_Leak25 { get; set; }
        public virtual DbSet<MozyrBK1_Level_TankLeak25_Scr4> MozyrBK1_Level_TankLeak25_Scr4 { get; set; }
        public virtual DbSet<MozyrNS2_Level_TanlLeak1_2> MozyrNS2_Level_TanlLeak1_2 { get; set; }
        public virtual DbSet<MozyrNS2_Level_TanlLeak25> MozyrNS2_Level_TanlLeak25 { get; set; }
        public virtual DbSet<MozyrNS3_Level_TankLeak47> MozyrNS3_Level_TankLeak47 { get; set; }
        public virtual DbSet<MozyrNS41_Level_TankLeak63> MozyrNS41_Level_TankLeak63 { get; set; }
        public virtual DbSet<PinskNS1_Level_TankLeak40> PinskNS1_Level_TankLeak40 { get; set; }
        public virtual DbSet<PinskNS2_Level_TankLeak200_1> PinskNS2_Level_TankLeak200_1 { get; set; }
        public virtual DbSet<PinskNS2_Level_TankLeak200_2> PinskNS2_Level_TankLeak200_2 { get; set; }
        public virtual DbSet<PinskNS2_Level_TankLeak25> PinskNS2_Level_TankLeak25 { get; set; }
        public virtual DbSet<PinskScr_Level_TankLeak25> PinskScr_Level_TankLeak25 { get; set; }
        public virtual DbSet<SIKN461_Level_TankLeak> SIKN461_Level_TankLeak { get; set; }
        public virtual DbSet<TurovNS1_Level_TankLeak12> TurovNS1_Level_TankLeak12 { get; set; }
        public virtual DbSet<TurovNS2_Level_TankLeak200_1> TurovNS2_Level_TankLeak200_1 { get; set; }
        public virtual DbSet<TurovNS2_Level_TankLeak200_2> TurovNS2_Level_TankLeak200_2 { get; set; }
        public virtual DbSet<ZaschNS1_Level_TankLeak25> ZaschNS1_Level_TankLeak25 { get; set; }
        public virtual DbSet<ZaschNS2_Level_TankLeak100_1> ZaschNS2_Level_TankLeak100_1 { get; set; }
        public virtual DbSet<ZaschNS2_Level_TankLeak100_2> ZaschNS2_Level_TankLeak100_2 { get; set; }
        public virtual DbSet<ZaschNS2_Level_TankLeak100_3> ZaschNS2_Level_TankLeak100_3 { get; set; }
        public virtual DbSet<ZaschNS2_Level_TankLeak200_1> ZaschNS2_Level_TankLeak200_1 { get; set; }
        public virtual DbSet<ZaschNS2_Level_TankLeak200_2> ZaschNS2_Level_TankLeak200_2 { get; set; }
        public virtual DbSet<GomelNS1_Level_TankLeak100_1> GomelNS1_Level_TankLeak100_1 { get; set; }
        public virtual DbSet<GomelNS1_Level_TankLeak100_2> GomelNS1_Level_TankLeak100_2 { get; set; }
        public virtual DbSet<GomelNS1_Level_TankLeak400_1> GomelNS1_Level_TankLeak400_1 { get; set; }
        public virtual DbSet<GomelNS2_Level_TankLeak400_2> GomelNS2_Level_TankLeak400_2 { get; set; }
        public virtual DbSet<TurovNS2_Level_TankLeak25_1> TurovNS2_Level_TankLeak25_1 { get; set; }
        public virtual DbSet<TurovNS2_Level_TankLeak25_2> TurovNS2_Level_TankLeak25_2 { get; set; }
        public virtual DbSet<MozyrNS5_Level_TankLeak461_1> MozyrNS5_Level_TankLeak461_1 { get; set; }
        public virtual DbSet<MozyrNS5_Level_TankLeak461_2> MozyrNS5_Level_TankLeak461_2 { get; set; }
        public virtual DbSet<MozyrNS41_Level_TankLeakMA63> MozyrNS41_Level_TankLeakMA63 { get; set; }
        public virtual DbSet<MozyrNS5_Level_TankLeak25> MozyrNS5_Level_TankLeak25 { get; set; }
        public virtual DbSet<MozyrBK18_Tank_Level_19> MozyrBK18_Tank_Level_19 { get; set; }
        public virtual DbSet<MozyrBK18_Tank_Level_20> MozyrBK18_Tank_Level_20 { get; set; }
    }
}
