//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservuary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tank_hour
    {
        public Nullable<int> tank_ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<double> oLevel { get; set; }
        public Nullable<double> oTemper { get; set; }
        public Nullable<double> oDensRef { get; set; }
        public int ID { get; set; }
    }
}
