//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservuary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurovNS2_Level_TankLeak200_1
    {
        public int id { get; set; }
        public Nullable<double> value { get; set; }
        public System.DateTime dt { get; set; }
        public int quality { get; set; }
    }
}
